sudo: true
os: trusty
cache: false
env:
- URL=https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
before_install:

- export SFDX_AUTOUPDATE_DISABLE=false
- export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
- export SFDX_DOMAIN_RETRY=300
- export SFDX_DISABLE_APP_HUB=true
- export SFDX_LOG_LEVEL=DEBUG
- mkdir sfdx
- wget -qO- $URL | tar xJ -C sfdx --strip-components 1
- "./sfdx/install"
- export PATH=./sfdx/$(pwd):$PATH
- sfdx --version
- sfdx force:auth:jwt:grant --clientid 3MVG92u_V3UMpV.hQHi5jeUtfhnh8vmLAdhYdinULoDo8OUzlHvSBAWtEgiQ09wLC6QEEHewdkhIrXuJ5kfFP --jwtkeyfile server.key --username test-dt3gldnzeagq@example.com --instanceurl https://test.salesforce.com --setdefaultdevhubusername -a travis
script:
- node --version
- sfdx force:org:display -u travis
